security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/register$, roles: PUBLIC_ACCESS }
        # Autoriser l’accès à la page de connexion
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        # Autoriser la déconnexion
        - { path: ^/logout$, roles: PUBLIC_ACCESS }
        # Bloquer tout le reste (page d’accueil, articles, catégories, etc.)
        - { path: ^/, roles: ROLE_USER }
